# Generated by CMake Nix Generator
with import <nixpkgs> {};
with pkgs;
with lib;

let
# Helper functions for DRY derivations

  cmakeNixCC = {
    name,
    src,
    compiler ? gcc,
    flags ? "",
    source,  # Source file path relative to src
    buildInputs ? [],
    propagatedInputs ? []
  }: stdenv.mkDerivation {
    inherit name src buildInputs propagatedInputs;
    dontFixup = true;
    buildPhase = ''
      mkdir -p "$(dirname "$out")"
      # Determine compiler binary name based on the compiler derivation
      compilerBin="${
        if compiler == gcc then
          "gcc"
        else if compiler == clang then
          "clang"
        else if compiler == gfortran then
          "gfortran"
        else
          compiler.pname or "cc"
      }"
      # When src is a directory, Nix unpacks it into a subdirectory
      # We need to find the actual source file
      # Store source in a variable to handle paths with spaces
      sourceFile="${source}"
      # Check if source is an absolute path or Nix expression (e.g., $\{derivation}/file)
      if [[ "$sourceFile" == /* ]] || [[ "$sourceFile" == *"$"* ]]; then
        # Absolute path or Nix expression - use as-is
        srcFile="$sourceFile"
      elif [[ -f "$sourceFile" ]]; then
        srcFile="$sourceFile"
      elif [[ -f "$(basename "$src")/$sourceFile" ]]; then
        srcFile="$(basename "$src")/$sourceFile"
      else
        echo "Error: Cannot find source file $sourceFile"
        exit 1
      fi
      ${compiler}/bin/$compilerBin -c ${flags} "$srcFile" -o "$out"
    '';
    installPhase = "true";
  };

  # Linking helper function
  # NOTE: This uses Unix-style library naming conventions (lib*.a, lib*.so)
  # This is appropriate since Nix only runs on Unix-like systems (Linux, macOS)
  cmakeNixLD = {
    name,
    type ? "executable",  # "executable", "static", "shared", "module"
    objects,
    compiler ? gcc,
    compilerCommand ? null,  # Override compiler binary name (e.g., "g++" for C++)
    flags ? "",
    libraries ? [],
    buildInputs ? [],
    version ? null,
    soversion ? null,
    postBuildPhase ? ""
  }: stdenv.mkDerivation {
    inherit name objects buildInputs;
    dontUnpack = true;
    buildPhase =
      if type == "static" then ''
        # Unix static library: uses 'ar' to create lib*.a files
        mkdir -p "$(dirname "$out")"
        ar rcs "$out" $objects
      '' else if type == "shared" || type == "module" then ''
        mkdir -p $out
        compilerBin="${if compilerCommand != null then
          compilerCommand
        else if compiler == gcc then
          "gcc"
        else if compiler == clang then
          "clang"
        else if compiler == gfortran then
          "gfortran"
        else
          compiler.pname or "cc"
        }";
        # Unix library naming: static=lib*.a, shared=lib*.so, module=*.so
        libname="${if type == "module" then name else "lib" + name}.so"
        ${if version != null && type != "module" then ''
          libname="lib${name}.so.${version}"
        '' else ""}
        ${compiler}/bin/$compilerBin -shared $objects ${flags} ${lib.concatMapStringsSep " " (l: l) libraries} -o "$out/$libname"
        # Create version symlinks if needed (only for shared libraries, not modules)
        ${if version != null && type != "module" then ''
          ln -sf "$libname" "$out/lib${name}.so"
          ${if soversion != null then ''
            ln -sf "$libname" "$out/lib${name}.so.${soversion}"
          '' else ""}
        '' else ""}
      '' else ''
        mkdir -p "$(dirname "$out")"
        compilerBin="${if compilerCommand != null then
          compilerCommand
        else if compiler == gcc then
          "gcc"
        else if compiler == clang then
          "clang"
        else if compiler == gfortran then
          "gfortran"
        else
          compiler.pname or "cc"
        }";
        ${compiler}/bin/$compilerBin $objects ${flags} ${lib.concatMapStringsSep " " (l: l) libraries} -o "$out"
      '';
    inherit postBuildPhase;
    installPhase = "true";
  };

# Per-translation-unit derivations
  config_test_build_test_config_test_cpp_o = cmakeNixCC {
    name = "config_test.o";
    src = ./..;
    buildInputs = [ gcc ];
    source = "build-test/config_test.cpp";
    compiler = gcc;
    flags = "-O2 -g -DNDEBUG -std=gnu++17 -DCMAKE_BUILD_TYPE_RELWITHDEBINFO -std=c++17";
  };

  opt_lib_build_test_config_test_cpp_o = cmakeNixCC {
    name = "config_test.o";
    src = ./..;
    buildInputs = [ gcc ];
    source = "build-test/config_test.cpp";
    compiler = gcc;
    flags = "-O2 -g -DNDEBUG -std=gnu++17 -std=c++17";
  };


  # Linking derivations
  link_config_test = cmakeNixLD {
    name = "config_test";
    type = "executable";
    buildInputs = [ gcc ];
    objects = [ config_test_build_test_config_test_cpp_o ];
    compiler = gcc;
    compilerCommand = "g++";
  };

  link_opt_lib = cmakeNixLD {
    name = "opt_lib";
    type = "static";
    buildInputs = [ gcc ];
    objects = [ opt_lib_build_test_config_test_cpp_o ];
    compiler = gcc;
    compilerCommand = "g++";
  };


  # Install derivations
  link_config_test_install = stdenv.mkDerivation {
    name = "config_test-install";
    src = link_config_test;
    dontUnpack = true;
    dontBuild = true;
    dontConfigure = true;
    installPhase = ''
      mkdir -p $out/bin/RelWithDebInfo
      cp $src $out/bin/RelWithDebInfo/config_test
    '';
  };

  link_opt_lib_install = stdenv.mkDerivation {
    name = "opt_lib-install";
    src = link_opt_lib;
    dontUnpack = true;
    dontBuild = true;
    dontConfigure = true;
    installPhase = ''
      mkdir -p $out/lib/RelWithDebInfo
      cp $src $out/lib/RelWithDebInfo/libopt_lib.a
    '';
  };

in
{
  "config_test" = link_config_test;
  "opt_lib" = link_opt_lib;
  "config_test_install" = link_config_test_install;
  "opt_lib_install" = link_opt_lib_install;
}
