# Generated by CMake Nix Generator
with import <nixpkgs> {};
with pkgs;
with lib;

let
# Helper functions for DRY derivations

  cmakeNixCC = {
    name,
    src,
    compiler ? gcc,
    flags ? "",
    source,  # Source file path relative to src
    buildInputs ? [],
    propagatedInputs ? []
  }: stdenv.mkDerivation {
    inherit name src buildInputs propagatedInputs;
    dontFixup = true;
    buildPhase = ''
      mkdir -p "$(dirname "$out")"
      # Determine compiler binary name based on the compiler derivation
      compilerBin="${
        if compiler == gcc then
          "gcc"
        else if compiler == clang then
          "clang"
        else if compiler == gfortran then
          "gfortran"
        else
          compiler.pname or "cc"
      }"
      # When src is a directory, Nix unpacks it into a subdirectory
      # We need to find the actual source file
      # Store source in a variable to handle paths with spaces
      sourceFile="${source}"
      # Check if source is an absolute path or Nix expression (e.g., $\{derivation}/file)
      if [[ "$sourceFile" == /* ]] || [[ "$sourceFile" == *"$"* ]]; then
        # Absolute path or Nix expression - use as-is
        srcFile="$sourceFile"
      elif [[ -f "$sourceFile" ]]; then
        srcFile="$sourceFile"
      elif [[ -f "$(basename "$src")/$sourceFile" ]]; then
        srcFile="$(basename "$src")/$sourceFile"
      else
        echo "Error: Cannot find source file $sourceFile"
        exit 1
      fi
      ${compiler}/bin/$compilerBin -c ${flags} "$srcFile" -o "$out"
    '';
    installPhase = "true";
  };

  # Linking helper function
  # NOTE: This uses Unix-style library naming conventions (lib*.a, lib*.so)
  # This is appropriate since Nix only runs on Unix-like systems (Linux, macOS)
  cmakeNixLD = {
    name,
    type ? "executable",  # "executable", "static", "shared", "module"
    objects,
    compiler ? gcc,
    compilerCommand ? null,  # Override compiler binary name (e.g., "g++" for C++)
    flags ? "",
    libraries ? [],
    buildInputs ? [],
    version ? null,
    soversion ? null,
    postBuildPhase ? ""
  }: stdenv.mkDerivation {
    inherit name objects buildInputs;
    dontUnpack = true;
    buildPhase =
      if type == "static" then ''
        # Unix static library: uses 'ar' to create lib*.a files
        mkdir -p "$(dirname "$out")"
        ar rcs "$out" $objects
      '' else if type == "shared" || type == "module" then ''
        mkdir -p $out
        compilerBin="${if compilerCommand != null then
          compilerCommand
        else if compiler == gcc then
          "gcc"
        else if compiler == clang then
          "clang"
        else if compiler == gfortran then
          "gfortran"
        else
          compiler.pname or "cc"
        }";
        # Unix library naming: static=lib*.a, shared=lib*.so, module=*.so
        libname="${if type == "module" then name else "lib" + name}.so"
        ${if version != null && type != "module" then ''
          libname="lib${name}.so.${version}"
        '' else ""}
        ${compiler}/bin/$compilerBin -shared $objects ${flags} ${lib.concatMapStringsSep " " (l: l) libraries} -o "$out/$libname"
        # Create version symlinks if needed (only for shared libraries, not modules)
        ${if version != null && type != "module" then ''
          ln -sf "$libname" "$out/lib${name}.so"
          ${if soversion != null then ''
            ln -sf "$libname" "$out/lib${name}.so.${soversion}"
          '' else ""}
        '' else ""}
      '' else ''
        mkdir -p "$(dirname "$out")"
        compilerBin="${if compilerCommand != null then
          compilerCommand
        else if compiler == gcc then
          "gcc"
        else if compiler == clang then
          "clang"
        else if compiler == gfortran then
          "gfortran"
        else
          compiler.pname or "cc"
        }";
        ${compiler}/bin/$compilerBin $objects ${flags} ${lib.concatMapStringsSep " " (l: l) libraries} -o "$out"
      '';
    inherit postBuildPhase;
    installPhase = "true";
  };

# Per-translation-unit derivations
  cmake_core_Source_cmSystemTools_cxx_o = cmakeNixCC {
    name = "cmSystemTools.o";
    src = pkgs.runCommand "composite-src" {} ''
      mkdir -p $out
      cp -rL ${./..}/* $out/ 2>/dev/null || true
      cp ${builtins.path { path = "/home/mpedersen/topics/cmake_nix_backend/CMake/Source/cmSystemTools.cxx"; }} $out/cmSystemTools.cxx
    '';
    buildInputs = [ gcc ];
    source = "cmSystemTools.cxx";
    compiler = gcc;
    flags = "-O3 -DNDEBUG -DCMAKE_BUILD_WITH_CMAKE -DKWSYS_NAMESPACE=cmsys -I/home/mpedersen/topics/cmake_nix_backend/CMake/test_cmake_self_host/../Source -I/home/mpedersen/topics/cmake_nix_backend/CMake/test_cmake_self_host/../Bootstrap.cmk";
  };

  cmake_core_Source_cmStringAlgorithms_cxx_o = cmakeNixCC {
    name = "cmStringAlgorithms.o";
    src = pkgs.runCommand "composite-src" {} ''
      mkdir -p $out
      cp -rL ${./..}/* $out/ 2>/dev/null || true
      cp ${builtins.path { path = "/home/mpedersen/topics/cmake_nix_backend/CMake/Source/cmStringAlgorithms.cxx"; }} $out/cmStringAlgorithms.cxx
    '';
    buildInputs = [ gcc ];
    source = "cmStringAlgorithms.cxx";
    compiler = gcc;
    flags = "-O3 -DNDEBUG -DCMAKE_BUILD_WITH_CMAKE -DKWSYS_NAMESPACE=cmsys -I/home/mpedersen/topics/cmake_nix_backend/CMake/test_cmake_self_host/../Source -I/home/mpedersen/topics/cmake_nix_backend/CMake/test_cmake_self_host/../Bootstrap.cmk";
  };

  cmake_core_Source_cmValue_cxx_o = cmakeNixCC {
    name = "cmValue.o";
    src = pkgs.runCommand "composite-src" {} ''
      mkdir -p $out
      cp -rL ${./..}/* $out/ 2>/dev/null || true
      cp ${builtins.path { path = "/home/mpedersen/topics/cmake_nix_backend/CMake/Source/cmValue.cxx"; }} $out/cmValue.cxx
    '';
    buildInputs = [ gcc ];
    source = "cmValue.cxx";
    compiler = gcc;
    flags = "-O3 -DNDEBUG -DCMAKE_BUILD_WITH_CMAKE -DKWSYS_NAMESPACE=cmsys -I/home/mpedersen/topics/cmake_nix_backend/CMake/test_cmake_self_host/../Source -I/home/mpedersen/topics/cmake_nix_backend/CMake/test_cmake_self_host/../Bootstrap.cmk";
  };

  cmake_test_app_test_cmake_self_host_test_main_cxx_o = cmakeNixCC {
    name = "test_main.o";
    src = ./..;
    buildInputs = [ gcc ];
    source = "test_main.cxx";
    compiler = gcc;
    flags = "-O3 -DNDEBUG -I/home/mpedersen/topics/cmake_nix_backend/CMake/test_cmake_self_host/../Source -I/home/mpedersen/topics/cmake_nix_backend/CMake/test_cmake_self_host/../Bootstrap.cmk";
  };


  # Linking derivations
  link_cmake_core = cmakeNixLD {
    name = "cmake_core";
    type = "static";
    buildInputs = [ gcc ];
    objects = [ cmake_core_Source_cmSystemTools_cxx_o cmake_core_Source_cmStringAlgorithms_cxx_o cmake_core_Source_cmValue_cxx_o ];
    compiler = gcc;
    compilerCommand = "g++";
  };

  link_cmake_test_app = cmakeNixLD {
    name = "cmake_test_app";
    type = "executable";
    buildInputs = [ gcc ];
    objects = [ cmake_test_app_test_cmake_self_host_test_main_cxx_o ];
    compiler = gcc;
    compilerCommand = "g++";
    flags = "${link_cmake_core} -lpthread";
  };

in
{
  "cmake_core" = link_cmake_core;
  "cmake_test_app" = link_cmake_test_app;
}
