# Generated by CMake Nix Generator
with import <nixpkgs> {};

let
  # Per-translation-unit derivations
  abi_test_main_c_o = stdenv.mkDerivation {
    name = "main.o";
    src = ./..;
    buildInputs = [ gcc ];
    dontFixup = true;
    # Configuration: Release
    buildPhase = ''
      gcc -c  "main.c" -o "$out"
    '';
    installPhase = "true"; # No install needed for objects
  };


  # Linking derivations
  link_abi_test = stdenv.mkDerivation {
    name = "abi_test";
    buildInputs = [ gcc ];
    dontUnpack = true;
    objects = [
      abi_test_main_c_o
    ];
    buildPhase = ''
      gcc $objects -o "$out"
    '';
    installPhase = "true"; # No install needed
  };


  # Install derivations
  link_abi_test_install = stdenv.mkDerivation {
    name = "abi_test-install";
    src = link_abi_test;
    dontUnpack = true;
    dontBuild = true;
    dontConfigure = true;
    installPhase = ''
      mkdir -p $out/bin $out/lib $out/include
      cp $src $out/bin/abi_test
    '';
  };

in
{
  "abi_test" = link_abi_test;
  "abi_test_install" = link_abi_test_install;
}
