# Generated by CMake Nix Generator
with import <nixpkgs> {};

let
  # Per-translation-unit derivations
  calculator_main_c_o = stdenv.mkDerivation {
    name = "main.o";
    src = ./main.c;
    buildInputs = [ gcc ];
    dontUnpack = true;
    dontFixup = true;
    buildPhase = ''
      gcc -c "$src" -o "$out"
    '';
    installPhase = "true"; # No install needed for objects
  };

  calculator_math_c_o = stdenv.mkDerivation {
    name = "math.o";
    src = ./math.c;
    buildInputs = [ gcc ];
    dontUnpack = true;
    dontFixup = true;
    buildPhase = ''
      gcc -c "$src" -o "$out"
    '';
    installPhase = "true"; # No install needed for objects
  };

  mathlib_math_c_o = stdenv.mkDerivation {
    name = "math.o";
    src = ./math.c;
    buildInputs = [ gcc ];
    dontUnpack = true;
    dontFixup = true;
    buildPhase = ''
      gcc -c "$src" -o "$out"
    '';
    installPhase = "true"; # No install needed for objects
  };

  mathlib_utils_c_o = stdenv.mkDerivation {
    name = "utils.o";
    src = ./utils.c;
    buildInputs = [ gcc ];
    dontUnpack = true;
    dontFixup = true;
    buildPhase = ''
      gcc -c "$src" -o "$out"
    '';
    installPhase = "true"; # No install needed for objects
  };


  # Linking derivations
  link_calculator = stdenv.mkDerivation {
    name = "calculator";
    buildInputs = [ gcc ];
    dontUnpack = true;
    objects = [
      calculator_main_c_o
      calculator_math_c_o
    ];
    buildPhase = ''
      gcc $objects -o "$out"
    '';
    installPhase = "true"; # No install needed
  };

  link_mathlib = stdenv.mkDerivation {
    name = "mathlib";
    buildInputs = [ gcc ];
    dontUnpack = true;
    objects = [
      mathlib_math_c_o
      mathlib_utils_c_o
    ];
    buildPhase = ''
      ar rcs "$out" $objects
    '';
    installPhase = "true"; # No install needed
  };

in
{
  "calculator" = link_calculator;
  "mathlib" = link_mathlib;
}
