default: clean configure run

clean:
    rm -f default.nix
    rm -rf CMakeFiles CMakeCache.txt cmake_install.cmake

configure:
    ../bin/cmake -G Nix .

build:
    nix-build -A fortran_test

run: clean configure build
    ./result && rm ./result

test: run
    @echo "✅ Fortran language test passed!"