#!/usr/bin/env just --justfile

# Clean up build artifacts
clean:
    rm -rf default.nix CMakeCache.txt CMakeFiles cmake_install.cmake

# Configure the project with CMake using Nix generator
configure:
    rm -f default.nix
    ../bin/cmake -G Nix -DCMAKE_MAKE_PROGRAM=nix-build .

# Build and run the test
run: clean configure
    @echo "=== Building JSON library example ==="
    nix-build -A json_example && ./result

# Build and test all targets
test: run