# Generated by CMake Nix Generator
with import <nixpkgs> {};

let
  # Per-translation-unit derivations
  explicit_test_test_explicit_sources_main_c_o = stdenv.mkDerivation {
    name = "main.o";
    src = stdenv.mkDerivation {
      name = "src_2ba7971b";
      dontUnpack = true;
      buildPhase = ''
        mkdir -p $out
        cp ${././main.c} $out/main.c
        mkdir -p $out/include
        cp ${././include/helper.h} $out/include/helper.h
      '';
      installPhase = "true";
    };
    buildInputs = [ gcc ];
    dontFixup = true;
    # Header dependencies
    propagatedInputs = [
      ./include/helper.h
    ];
    # Configuration: Release
    buildPhase = ''
      gcc -c -O3 -DNDEBUG -Iinclude "main.c" -o "$out"
    '';
    installPhase = "true"; # No install needed for objects
  };

  explicit_test_utils_helper_c_o = stdenv.mkDerivation {
    name = "helper.o";
    src = stdenv.mkDerivation {
      name = "src_fa80a247";
      dontUnpack = true;
      buildPhase = ''
        mkdir -p $out
        mkdir -p $out/utils
        cp ${././utils/helper.c} $out/utils/helper.c
        mkdir -p $out/include
        cp ${././include/helper.h} $out/include/helper.h
        mkdir -p $out/include
        cp ${././include/internal.h} $out/include/internal.h
      '';
      installPhase = "true";
    };
    buildInputs = [ gcc ];
    dontFixup = true;
    # Header dependencies
    propagatedInputs = [
      ./include/helper.h
      ./include/internal.h
    ];
    # Configuration: Release
    buildPhase = ''
      gcc -c -O3 -DNDEBUG -Iinclude "utils/helper.c" -o "$out"
    '';
    installPhase = "true"; # No install needed for objects
  };


  # Linking derivations
  link_explicit_test = stdenv.mkDerivation {
    name = "explicit_test";
    buildInputs = [ gcc ];
    dontUnpack = true;
    objects = [
      explicit_test_test_explicit_sources_main_c_o
      explicit_test_utils_helper_c_o
    ];
    buildPhase = ''
      gcc $objects -o "$out"
    '';
    installPhase = "true"; # No install needed
  };

in
{
  "explicit_test" = link_explicit_test;
}
