# Generated by CMake Nix Generator
with import <nixpkgs> {};

let
  # Per-translation-unit derivations
  selfhost_demo_simple_demo_cpp_o = stdenv.mkDerivation {
    name = "simple_demo.o";
    src = ./.;
    buildInputs = [ gcc ];
    dontFixup = true;
    # Configuration: Release
    buildPhase = ''
      g++ -c  "simple_demo.cpp" -o "$out"
    '';
    installPhase = "true"; # No install needed for objects
  };

  demo_utils_demo_utils_cpp_o = stdenv.mkDerivation {
    name = "demo_utils.o";
    src = ./.;
    buildInputs = [ gcc ];
    dontFixup = true;
    # Configuration: Release
    buildPhase = ''
      g++ -c  "demo_utils.cpp" -o "$out"
    '';
    installPhase = "true"; # No install needed for objects
  };


  # Linking derivations
  link_selfhost_demo = stdenv.mkDerivation {
    name = "selfhost_demo";
    buildInputs = [ gcc ];
    dontUnpack = true;
    objects = [
      selfhost_demo_simple_demo_cpp_o
    ];
    buildPhase = ''
      g++ $objects ${link_demo_utils} -o "$out"
    '';
    installPhase = "true"; # No install needed
  };

  link_demo_utils = stdenv.mkDerivation {
    name = "demo_utils";
    buildInputs = [ gcc ];
    dontUnpack = true;
    objects = [
      demo_utils_demo_utils_cpp_o
    ];
    buildPhase = ''
      ar rcs "$out" $objects
    '';
    installPhase = "true"; # No install needed
  };


  # Install derivations
  link_selfhost_demo_install = stdenv.mkDerivation {
    name = "selfhost_demo-install";
    src = link_selfhost_demo;
    dontUnpack = true;
    dontBuild = true;
    dontConfigure = true;
    installPhase = ''
      mkdir -p $out/bin $out/lib $out/include
      cp $src $out/bin/selfhost_demo
    '';
  };

  link_demo_utils_install = stdenv.mkDerivation {
    name = "demo_utils-install";
    src = link_demo_utils;
    dontUnpack = true;
    dontBuild = true;
    dontConfigure = true;
    installPhase = ''
      mkdir -p $out/bin $out/lib $out/include
      cp $src $out/lib/libdemo_utils.a
    '';
  };

in
{
  "selfhost_demo" = link_selfhost_demo;
  "demo_utils" = link_demo_utils;
  "selfhost_demo_install" = link_selfhost_demo_install;
  "demo_utils_install" = link_demo_utils_install;
}
