/* Distributed under the OSI-approved BSD 3-Clause License.  See accompanying
   file LICENSE.rst or https://cmake.org/licensing for details.  */
#include "cmGlobalNixGenerator.h"

#include <cm/memory>
#include <iostream>
#include <sstream>
#include <algorithm>

#include "cmGeneratedFileStream.h"
#include "cmGeneratorTarget.h"
#include "cmLocalNixGenerator.h"
#include "cmMakefile.h"
#include "cmSourceFile.h"
#include "cmSystemTools.h"
#include "cmake.h"

cmGlobalNixGenerator::cmGlobalNixGenerator(cmake* cm)
  : cmGlobalCommonGenerator(cm)
{
  // Set the make program file
  this->FindMakeProgramFile = "CMakeNixFindMake.cmake";
}

std::unique_ptr<cmLocalGenerator> cmGlobalNixGenerator::CreateLocalGenerator(
  cmMakefile* mf)
{
  return std::unique_ptr<cmLocalGenerator>(
    cm::make_unique<cmLocalNixGenerator>(this, mf));
}

cmDocumentationEntry cmGlobalNixGenerator::GetDocumentation()
{
  return { cmGlobalNixGenerator::GetActualName(),
           "Generates Nix expressions for building C/C++ projects with "
           "fine-grained derivations for maximal parallelism and caching." };
}

void cmGlobalNixGenerator::Generate()
{
  // First call the parent Generate to set up targets
  this->cmGlobalGenerator::Generate();
  
  // Generate our Nix output
  this->WriteNixFile();
}

std::vector<cmGlobalGenerator::GeneratedMakeCommand>
cmGlobalNixGenerator::GenerateBuildCommand(
  std::string const& makeProgram, std::string const& /*projectName*/,
  std::string const& /*projectDir*/,
  std::vector<std::string> const& targetNames, std::string const& /*config*/,
  int /*jobs*/, bool /*verbose*/, cmBuildOptions const& /*buildOptions*/,
  std::vector<std::string> const& /*makeOptions*/)
{
  GeneratedMakeCommand makeCommand;
  
  // For Nix generator, we use nix-build as the build program
  makeCommand.Add(this->SelectMakeProgram(makeProgram, "nix-build"));
  
  // Add default.nix file
  makeCommand.Add("default.nix");
  
  // Add target names as attribute paths  
  for (auto const& tname : targetNames) {
    if (!tname.empty()) {
      makeCommand.Add("-A", tname);
    }
  }
  
  return { std::move(makeCommand) };
}

void cmGlobalNixGenerator::WriteNixFile()
{
  std::string nixFile = this->GetCMakeInstance()->GetHomeOutputDirectory();
  nixFile += "/default.nix";
  
  cmGeneratedFileStream nixFileStream(nixFile);
  nixFileStream.SetCopyIfDifferent(true);
  
  if (!nixFileStream) {
    return;
  }

  // Write Nix file header
  nixFileStream << "# Generated by CMake Nix Generator\n"
                << "with import <nixpkgs> {};\n\n"
                << "let\n";

  // Write per-translation-unit derivations
  this->WritePerTranslationUnitDerivations(nixFileStream);
  
  // Write linking derivations
  this->WriteLinkingDerivations(nixFileStream);
  
  nixFileStream << "in\n{\n";
  
  // Write final target outputs
  for (auto const& lg : this->LocalGenerators) {
    auto const& targets = lg->GetGeneratorTargets();
    for (auto const& target : targets) {
      if (target->GetType() == cmStateEnums::EXECUTABLE ||
          target->GetType() == cmStateEnums::STATIC_LIBRARY ||
          target->GetType() == cmStateEnums::SHARED_LIBRARY) {
        nixFileStream << "  \"" << target->GetName() << "\" = "
                      << this->GetDerivationName(target->GetName()) << ";\n";
      }
    }
  }
  
  nixFileStream << "}\n";
}

void cmGlobalNixGenerator::WritePerTranslationUnitDerivations(
  cmGeneratedFileStream& nixFileStream)
{
  nixFileStream << "  # Per-translation-unit derivations\n";
  
  for (auto const& lg : this->LocalGenerators) {
    auto const& targets = lg->GetGeneratorTargets();
    for (auto const& target : targets) {
      if (target->GetType() == cmStateEnums::EXECUTABLE ||
          target->GetType() == cmStateEnums::STATIC_LIBRARY ||
          target->GetType() == cmStateEnums::SHARED_LIBRARY) {
        
        // Get source files for this target
        std::vector<cmSourceFile*> sources;
        target->GetSourceFiles(sources, "");
        
        for (cmSourceFile* source : sources) {
          std::string const& lang = source->GetLanguage();
          if (lang == "C" || lang == "CXX") {
            this->WriteObjectDerivation(nixFileStream, target.get(), source);
          }
        }
      }
    }
  }
}

void cmGlobalNixGenerator::WriteLinkingDerivations(
  cmGeneratedFileStream& nixFileStream)
{
  nixFileStream << "\n  # Linking derivations\n";
  
  for (auto const& lg : this->LocalGenerators) {
    auto const& targets = lg->GetGeneratorTargets();
    for (auto const& target : targets) {
      if (target->GetType() == cmStateEnums::EXECUTABLE ||
          target->GetType() == cmStateEnums::STATIC_LIBRARY ||
          target->GetType() == cmStateEnums::SHARED_LIBRARY) {
        this->WriteLinkDerivation(nixFileStream, target.get());
      }
    }
  }
}

std::string cmGlobalNixGenerator::GetDerivationName(
  std::string const& targetName, std::string const& sourceFile) const
{
  if (sourceFile.empty()) {
    return "link_" + targetName;
  }
  
  // Use just the filename, not the full path
  std::string filename = cmSystemTools::GetFilenameName(sourceFile);
  
  // Convert filename to valid Nix identifier
  std::string name = filename;
  std::replace(name.begin(), name.end(), '.', '_');
  return targetName + "_" + name + "_o";
}

void cmGlobalNixGenerator::WriteObjectDerivation(
  cmGeneratedFileStream& nixFileStream, cmGeneratorTarget* target, 
  cmSourceFile* source)
{
  std::string sourceFile = source->GetFullPath();
  std::string derivName = this->GetDerivationName(target->GetName(), sourceFile);
  std::string objectName = cmSystemTools::GetFilenameWithoutLastExtension(
    cmSystemTools::GetFilenameName(sourceFile)) + ".o";
  
  nixFileStream << "  " << derivName << " = stdenv.mkDerivation {\n";
  nixFileStream << "    name = \"" << objectName << "\";\n";
  nixFileStream << "    src = ./" << cmSystemTools::RelativePath(
    this->GetCMakeInstance()->GetHomeOutputDirectory(), sourceFile) << ";\n";
  nixFileStream << "    buildInputs = [ gcc ];\n";
  nixFileStream << "    dontUnpack = true;\n";
  nixFileStream << "    dontFixup = true;\n";  // Skip ELF fixup for object files
  nixFileStream << "    buildPhase = ''\n";
  nixFileStream << "      gcc -c \"$src\" -o \"$out\"\n";
  nixFileStream << "    '';\n";
  nixFileStream << "    installPhase = \"true\"; # No install needed for objects\n";
  nixFileStream << "  };\n\n";
}

void cmGlobalNixGenerator::WriteLinkDerivation(
  cmGeneratedFileStream& nixFileStream, cmGeneratorTarget* target)
{
  std::string derivName = this->GetDerivationName(target->GetName());
  std::string targetName = target->GetName();
  
  nixFileStream << "  " << derivName << " = stdenv.mkDerivation {\n";
  nixFileStream << "    name = \"" << targetName << "\";\n";
  nixFileStream << "    buildInputs = [ gcc ];\n";
  nixFileStream << "    dontUnpack = true;\n";  // No source to unpack
  
  // Collect object file dependencies
  std::vector<cmSourceFile*> sources;
  target->GetSourceFiles(sources, "");
  
  nixFileStream << "    objects = [\n";
  for (cmSourceFile* source : sources) {
    std::string const& lang = source->GetLanguage();
    if (lang == "C" || lang == "CXX") {
      std::string objDerivName = this->GetDerivationName(
        target->GetName(), source->GetFullPath());
      nixFileStream << "      " << objDerivName << "\n";
    }
  }
  nixFileStream << "    ];\n";
  
  nixFileStream << "    buildPhase = ''\n";
  if (target->GetType() == cmStateEnums::EXECUTABLE) {
    nixFileStream << "      gcc $objects -o \"$out\"\n";
  } else if (target->GetType() == cmStateEnums::STATIC_LIBRARY) {
    nixFileStream << "      ar rcs \"$out\" $objects\n";
  } else if (target->GetType() == cmStateEnums::SHARED_LIBRARY) {
    nixFileStream << "      gcc -shared $objects -o \"$out\"\n";
  }
  nixFileStream << "    '';\n";
  nixFileStream << "    installPhase = \"true\"; # No install needed\n";
  nixFileStream << "  };\n\n";
}

std::vector<std::string> cmGlobalNixGenerator::GetSourceDependencies(
  std::string const& /*sourceFile*/) const
{
  // TODO: Implement header dependency tracking
  // This will use CMake's existing dependency analysis
  return {};
} 